name: run-tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 7.3, 7.2]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: dependencies-laravel-php-${{ matrix.php }}-${{ matrix.dependency-version}}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: php-cs-test
        run: bin/php-cs-test

      - name: php-md-test
        run: bin/php-md-test ./src

      - name: php-tlint-test
        run: bin/php-tlint-test

      - name: php-insights-test
        run: bin/php-insights-test

      - name: php-stan-test
        run: bin/php-stan-test
