name: run-tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 7.3 ]
        laravel: [ 8.*, 7.* ]

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: dependencies-laravel-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            dependencies-laravel-php-${{ matrix.php }}-composer-
            dependencies-laravel-php-

      - name: Install dependencies
        run: |
          composer require --dev "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

      - run: bin/php-cs-test
      - run: bin/php-mn-test ./src
      - run: bin/php-md-test ./src
      - run: bin/php-tlint-test ./src
      - run: bin/php-insights-test
      - run: bin/php-stan-test
